public enum RenderMode
{
    DIRECT_VOLUME_RENDERING,
    MAXIMUM_INTENSITY_PROJECTION,
    ISOSURFACE,
    CURVATRE_BASED_IMPORTANCE,
    DISTANCE_BASED_IMPORTANCE,
    VIEW_DISTANCE_BASED_IMPORTANCE
}
